### ISSUE TITLE
a little problem

### ISSUE THREAD

**Issue by cxxz16** [Byzero512/winpwn#7]
when i debugging an AMD64 program, i can't see the registers like debugging i386 program, and it will throw a exception: c0000005 Exception in debugger client IDebugEventCallbacks::ChangeEngineState callback. Have u ever met? Thanks

**Comment by Byzero512** [comment]
no, maybe 32 bits debugger is used to debug the 64 bits process.

**Comment by Byzero512** [comment]
> when i debugging an AMD64 program, i can't see the registers like debugging i386 program, and it will throw a exception: c0000005 Exception in debugger client IDebugEventCallbacks::ChangeEngineState callback. Have u ever met? Thanks



> when i debugging an AMD64 program, i can't see the registers like debugging i386 program, and it will throw a exception: c0000005 Exception in debugger client IDebugEventCallbacks::ChangeEngineState callback. Have u ever met? Thanks
no, maybe 32 bits debugger is used to debug the 64 bits process.

**Comment by Byzero512** [comment]
> when i debugging an AMD64 program, i can't see the registers like debugging i386 program, and it will throw a exception: c0000005 Exception in debugger client IDebugEventCallbacks::ChangeEngineState callback. Have u ever met? Thanks

no, maybe 32 bits debugger is used to debug the 64 bits process.

**Comment by cxxz16** [comment]
ok thank u
